vimrc enhancement tmux.conf

diff --git a/default/templates/zshrc.j2 b/default/templates/zshrc.j2
--- a/default/templates/zshrc.j2
+++ b/default/templates/zshrc.j2
@@ -1,4 +1,11 @@
 {% raw %}
+if [ "$PS1" != "" -a "${STARTED_TMUX:-x}" = x -a "${SSH_TTY:-x}" != x ]
+then
+    STARTED_TMUX=1; export STARTED_TMUX
+    sleep 1
+    ( (tmux has-session -t $USER && tmux attach-session -t $USER) || (tmux new-session -s $USER) ) && exit 0
+    echo "tmux failed to start"
+fi
 # Path to your oh-my-zsh configuration.
 ZSH=$HOME/.oh-my-zsh
 
